### ISSUE TITLE
Compilers warnings

### ISSUE THREAD

**Issue by coin-au-carre** [martinmoene/lest#18]
Just to notice some compilers warning when using the ` -Wall` flag with Clang 3.7 : 

> warning: suggest braces around initialization of subobject [-Wmissing-braces]
>       CASE("test")
> lest.hpp:115:5: note: expanded from macro 'lest_CASE'
>    proposition, [__VA_ARGS__]( lest::env & $ )

and with the ` -pedantic`  flag GCC 5.2 tells : 
> warning: ISO C++11 requires at least one argument for the "..." in a variadic macro
> CASE("test")

with the ` -pedantic` flag Clang says lots of warnings of the type :  

> lest.hpp:172:27: warning: '$' in identifier [-Wdollar-in-identifier-extension]
> lest::report( $.os, lest::got_none( lest_LOCATION, #expr ), $.testing ); \

We also get some warnings with ` Weffc++`  flag

Thank you for this work I really enjoy it !

**Comment by martinmoene** [comment]
Resolved by pr #19.
