### ISSUE TITLE
JUnit compatible report

### ISSUE THREAD

**Issue by yury-khrustalev** [martinmoene/lest#32]
Do you plan to support saving test results as a report file, e.g. JUnit compatible?
This may be useful for showing test results in Jenkins and similar systems.

**Comment by martinmoene** [comment]
No, I don't have plans to do so. (If I recall correctly, I may have pondered with the idea to create an output filter to do so, but never actually made one.)

**Comment by yury-khrustalev** [comment]
Thank you for your reply
