### ISSUE TITLE
Autoregistration + multiple files => multiple definition of __lest_function__#

### ISSUE THREAD

**Issue by ianmacs** [martinmoene/lest#33]
Using lest.hpp with -Dlest_FEATURE_AUTO_REGISTER=1 and multiple files, I encounter a compilation error. This is the minimal example demonstrating the error:

File "f1.cc":
```
#define lest_FEATURE_AUTO_REGISTER 1
#include "lest.hpp"
extern lest::tests specs;
lest_CASE(specs,"f1") {EXPECT(false);}
```

File "f2.cc":
```
#define lest_FEATURE_AUTO_REGISTER 1
#include "lest.hpp"
lest::tests specs;
lest_CASE(specs,"f2") {EXPECT(false);}
int main(int n,char**a) {return lest::run(specs,n,a);}
```

Both files have a "lest_CASE" on line 4. The error when compiling with `g++-5 -std=c++11 f*.cc` is:
```/tmp/ccDEaxj8.o: In function `__lest_function__4(lest::env&)':
f2.cc:(.text+0x0): multiple definition of `__lest_function__4(lest::env&)'
/tmp/ccdEslkw.o:f1.cc:(.text+0x0): first defined here
collect2: error: ld returned 1 exit status```

**Comment by martinmoene** [comment]
For the multiple-file auto-test-registration case, in each source file place the test cases in an anonymous namespace.

See (from the Readme):
- [Auto test registration with multiple source files](https://github.com/martinmoene/lest/blob/master/README.md#test-case-macro) &ndash; [example part  1](https://github.com/martinmoene/lest/blob/master/example/13-module-auto-reg-1.cppp), [2](https://github.com/martinmoene/lest/blob/master/example/13-module-auto-reg-2.cpp), [3](https://github.com/martinmoene/lest/blob/master/example/13-module-auto-reg-3.cpp).

**Comment by ianmacs** [comment]
I understand.
I experimented with this and came up with this https://github.com/martinmoene/lest/pull/34 solution.
I like this better. static means local to the compilation unit here. If I am not missing something, then there is no need for global visibility of the test function.

**Comment by martinmoene** [comment]
It's likely caused by the undefined order of initialization across translation units of non-local variables with static storage duration, also called the [“static initialization order fiasco”](https://isocpp.org/wiki/faq/ctors#static-init-order).

The result depends on the order of f1.cc and f2.cc on the command line (g++ 5.2.0):
```
prompt> g++ -std=c++11 f1.cc f2.cc && a.exe
f2.cc:4: failed: f2: false for false
f1.cc:4: failed: f1: false for false
2 out of 2 selected tests failed.
```
and
```
prompt> g++ -std=c++11 f2.cc f1.cc && a.exe
f2.cc:4: failed: f2: false for false
1 out of 1 selected test failed.
```
The undefined initialization order is sidestepped by using a function-local static variable for the list of tests that is initialized on first-use (a [Meyer's singleton]()).
