### ISSUE TITLE
Intermediate informational text is discarded

### ISSUE THREAD

**Issue by Espressosaurus** [martinmoene/lest#35]
Error messages only display the text in CASE/SCENARIO.

Using a similar technique to Catch, it should be possible to propagate text from GIVEN/SETUP and SECTION/CASE to the reporter to give output looking something like:

`Failed:
Scenario:  Testing single-threaded container operations
Given:  A container of size 5
When:  No items are in the container
(decomposition, etc.)`

Unfortunately, this will not be a simple one or two-liner:  at minimum we're talking the creation of a helper class, a helper function, changes to the SETUP and SECTION macros, and changes to reporting.

Because this is a non-trivial change, I wanted to open the discussion on testing, style, and anything else you think is appropriate before I open a pull request.

**Comment by martinmoene** [comment]
As it is now, the reporting is only useful insofar that you can directly jump to the failing assert in the IDE.

I'm aware of it, but didn't see a solution that fits _lest_'s simplicity when I was at it (and forgot to create an issue for it). _lest_ is supposed to stay significantly simpler than [CATCH](https://github.com/philsquared/Catch) and [stf](https://github.com/jfalcou/stf) and [doctest](https://github.com/onqtam/doctest). One of the aspects I care about is that it can be easily overseen/read/studied.

I'm interested to see what your suggestions lead to, however I'll only be able to have a serious look at it from the second week in August.

**Comment by Espressosaurus** [comment]
The use case it's intended to help with is using helper functions in tests, where the line isn't as helpful, but the context would tell you what's going on.

I'll clean this up, fix the test bench, and see what you think.

**Comment by martinmoene** [comment]
Looking forward to it!

**Comment by Espressosaurus** [comment]
Pull request open, and I look forward to your feedback.

**Comment by martinmoene** [comment]
Now being developed per issue #61.
