### ISSUE TITLE
Add some reporting in case of success to the example

### ISSUE THREAD

**Issue by jjl** [martinmoene/lest#41]
I suspect I'm not the only one who feels more comfortable when they get some sort of message rather than total quiet (which suggests brokenness to me).

I think the main in the example should look like this (or the iostreams equivalent):

```c++
int main(int argc, char *argv[]) {
  int ret = lest::run(specification, argc, argv);
  if (ret == 0)
    printf("All tests succeeded\n");
  return ret;
}
```

**Comment by martinmoene** [comment]
Thanks @jjl,

I've covered this now in section [Main](https://github.com/martinmoene/lest#main).
