### ISSUE TITLE
A question regarding accessing private or protected variable

### ISSUE THREAD

**Issue by mizhang** [martinmoene/lest#45]
I am new to this test framework.  Wondering what is the standard way to access private or protected variables or functions to test in this framework.  Didn't find useful results form google, so asking it here. 

Thanks a lot!

**Comment by martinmoene** [comment]
*lest* has no support for directly accessing private or protected members. 

You may test :
1. indirectly via the public interface
2. by extracting more involved code into it's own class with a public interface
3. via a derived class (for protected members), 
   `struct TestClass : TestedClass { using protected_function; };`
4. via injecting the likes of `friend class Tester;`
5. ...

Refrain from doing
```
#define protected public
#define private public
#include "foo.hpp"
```
If foo.hpp happens to #include stuff, especially something from std it can easily backfire.

Note: Information obtained from a thread of [ACCU.org](http://accu.org)'s accu-general mailing list.

**Comment by mizhang** [comment]
Thanks!!  Miya  





On Wed, Jun 7, 2017 4:41 PM, Martin Moene notifications@github.com  wrote:
lest  has no support for directly accessing private or protected members.

You may test :

 1. indirectly via the public interface
 2. by extracting more involved code into it's own class with a public interface
 3. via a derived class (for protected members),
    struct TestClass : TestedClass { using protected_function; };
 4. via injecting the likes of friend class Tester;
 5. ...

Refrain from doing

#define protected public
#define private public
#include "foo.hpp"


If foo.hpp happens to #include stuff, especially something from std it can
easily backfire.

Note: Information obtained from a thread of ACCU.org's accu-general mailing
list.
