### ISSUE TITLE
Tests are failing after importing the project trouygh CMake

### ISSUE THREAD

**Issue by jgaa** [martinmoene/lest#56]
I imported lest in a simple CMake library project in kdevelop under Debian. 

In the Unit Tests pane, I see my test, and also tests from lest (which is good). However, when I run the tests, most of them fails. 

My tests pass, and the library seems to work.

Below is a screen-shot of the unit tests pane in kdevelop, after running all the tests,

![lest](https://user-images.githubusercontent.com/3822637/32796877-b4bc676a-c978-11e7-8f91-3315e573b814.png)

My project is here: [warlib](https://github.com/jgaa/warlib)

**Comment by martinmoene** [comment]
The numbered 'tests' are actually [examples](https://github.com/martinmoene/lest#usage) of which several fail for educational reasons.

CMake variable `LEST_BUILD_EXAMPLE` lets you control inclusion of the examples in the build process; by default it's on.

**Comment by jgaa** [comment]
That fixed it. Thank you.
