### ISSUE TITLE
SETUP & SECTION reporting

### ISSUE THREAD

**Issue by Beatrate** [martinmoene/lest#61]
It would be beneficial to have the SECTION names be reported with their success status. As it is now, their names are silently ignored and all asserts are just printed with the title of the outermost CASE. I think it would bring more granular control of tests where we can see the failing subtest's goal right away.

I suggest reporting them like this
```
1>main.cpp(39): Ill formed URLs are rejected
1>main.cpp(40): ====passed: Empty URL is rejected: FailParse("") for true
1>main.cpp(50): ====passed: URL with invalid protocol is rejected: FailParse("htt://some.org") for true
```
Where the CASE is "Ill formed URLs are rejected" and the rest are SECTIONs inside the case's setup.
This format could be a special verbose mode activated with the corresponding --verbose parameter.

**Comment by martinmoene** [comment]
> It would be beneficial to have the SECTION names be reported with their success status.

I do agree.

There's a longstanding PR on this subject: *Added reporting of intermediate description text from nested CASE, SETUP, and SECTIONs* (PR  #36).

*lest* is intended to be small and relatively simple, attributes I'm keen to keep (see e.g. [the way sections are handled](https://github.com/martinmoene/lest/blob/35606ac7f88b841be48b1f62b901f04ecbb601c5/include/lest/lest.hpp#L138)). I've yet to find a way to add reporting of sections in a manner that fits *lest*.

**Comment by martinmoene** [comment]
Perhaps, I should take a look at PR #36 again.
